name: Documentation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: https://meyer-nils.github.io/torch-fem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install zensical mkdocs mkdocstrings-python       
      - run: zensical build --clean

      - run: df -h
      
      - name: "node-cleanup"
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - run: df -h

      - name: Set up headless display
        run: |
          sudo apt install -y libgl1 libglx-mesa0 xvfb
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Install torch-fem and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter nbconvert
          python -m pip install .

      - name: Convert planar notebooks to HTML
        run: |
          jupyter nbconvert --to HTML --execute --output-dir site/examples/basic/planar/ examples/basic/planar/*.ipynb
          jupyter nbconvert --to HTML --output-dir site/examples/optimization/planar/ examples/optimization/planar/*.ipynb

      - name: Convert truss notebooks to HTML
        env:
          DISPLAY: ":99"
        run: |
          echo "DISPLAY variable: $DISPLAY"
          jupyter nbconvert --to HTML --execute --output-dir site/examples/basic/truss/ examples/basic/truss/*.ipynb
          jupyter nbconvert --to HTML --output-dir site/examples/optimization/truss/ examples/optimization/truss/*.ipynb

      - name: Convert shell notebooks to HTML
        env:
          DISPLAY: ":99"
        run: |
          echo "DISPLAY variable: $DISPLAY"
          jupyter nbconvert --to HTML --execute --output-dir site/examples/basic/shell/ examples/basic/shell/*.ipynb

      - name: Convert solid notebooks to HTML
        env:
          DISPLAY: ":99"
        run: |
          echo "DISPLAY variable: $DISPLAY"
          jupyter nbconvert --to HTML --execute --output-dir site/examples/basic/solid/ examples/basic/solid/*.ipynb
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment
